apps/web/lib/web/router.ex
defmodule Web.Router do
  use Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :api_auth do
    plug Guardian.Plug.VerifyHeader, realm: "Bearer"
    plug Guardian.Plug.LoadResource
  end

  scope "/", Web do
    pipe_through :browser

    get "/.well-known/amorphos", PageController, :host_information

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create]

    get "/login", PageController, :login
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete
    get "/switch-user", SessionController, :switch

    get "/timeline", EventController, :timeline

    scope "/yayaka" do
      get "/", YayakaUserController, :index
      get "/user-attributes", YayakaUserController, :user_attributes
      post "/create-user", YayakaUserController, :create_user
      post "/check-user-name-availability", YayakaUserController, :check_user_name_availability
      post "/update-user-name", YayakaUserController, :update_user_name
      post "/update-user-attributes", YayakaUserController, :update_user_attributes
      post "/fetch-user", YayakaUserController, :fetch_user
      post "/fetch-user-by-name", YayakaUserController, :fetch_user_by_name
      post "/get-token", YayakaUserController, :get_token
      post "/authenticate-user", YayakaUserController, :authenticate_user
      post "/authorize-service", YayakaUserController, :authorize_service
      post "/revoke-service-authorization", YayakaUserController, :revoke_service_authorization
      post "/fetch-user-relations", YayakaUserController, :fetch_user_relations
      post "/subscribe", YayakaUserController, :subscribe
      post "/unsubscribe", YayakaUserController, :unsubscribe
    end
  end

  scope "/api", Web do
    pipe_through [:api, :api_auth]

    scope "/amorphos" do
      scope "/https-token" do
        post "/request", HTTPSTokenController, :request
        post "/grant", HTTPSTokenController, :grant
        post "/packet", HTTPSTokenController, :packet
      end
    end
  end
end

apps/web/lib/web/views/layout_view.ex
defmodule Web.LayoutView do
  use Web, :view

  def render_user(user) do
    {:ok, user} = Yayaka.YayakaUserCache.get_or_fetch(user)
    "#{user.name} @ #{user.host}"
  end
end

apps/web/lib/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Web!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/semantic-ui/2.2.10/semantic.min.css" integrity="sha256-5+W3JHnvGYIJkVxUBsw+jBi9+pOlu9enPX3vZapXj5M=" crossorigin="anonymous">
  </head>

  <body>
    <div class="ui container">
      <div class="ui large menu">
        <a class="item" href="<%= page_path(@conn, :index) %>">
          Yayaka Reference
        </a>
        <div class="right menu">
          <% user = get_user(@conn) %>
          <% yayaka_user = get_yayaka_user(@conn) %>
          <%= if user do %>
            <div class="ui dropdown item">
              <%= if yayaka_user do %>
                <div class="text"><%= render_user(yayaka_user) %></div>
              <% else %>
                <div class="text"><%= user.name %></div>
              <% end %>
              <i class="dropdown icon"></i>
              <div class="menu">
                <a class="item" href="<%= yayaka_user_path(@conn, :index) %>">Yayaka API</a>
                <%= for link <- get_user_links(user) do %>
                  <% host = link.user.host %>
                  <% id = link.user.id %>
                  <a class="item" href="<%= session_path(@conn, :switch, host: host, id: id) %>">
                    <%= render_user(link.user) %>
                  </a>
                <% end %>
                <a class="item" href="<%= session_path(@conn, :delete) %>">Sign out</a>
              </div>
            </div>
          <% else %>
            <a class="item" href="<%= page_path(@conn, :login) %>">Sign in</a>
            <a class="item" href="<%= user_path(@conn, :new) %>">Sign up</a>
          <% end %>
        </div>
      </div>

      <pre class="ui message" role="alert"><%= get_flash(@conn, :info) %></pre>
      <pre class="ui message" role="alert"><%= get_flash(@conn, :error) %></pre>

      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g=" crossorigin="anonymous"></script>

      <main role="main" class="ui basic segment">
        <div class="ui container">
          <%= render @view_module, @view_template, assigns %>
        </div>
      </main>

    </div>
    <script src="https://cdn.jsdelivr.net/semantic-ui/2.2.10/semantic.min.js" integrity="sha256-97Q90i72uoJfYtVnO2lQcLjbjBySZjLHx50DYhCBuJo=" crossorigin="anonymous"></script>
    <script>
      $('.ui.dropdown').dropdown();
    </script>
  </body>
</html>