apps/web/lib/web/router.ex
defmodule Web.Router do
  use Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :api_auth do
    plug Guardian.Plug.VerifyHeader, realm: "Bearer"
    plug Guardian.Plug.LoadResource
  end

  scope "/", Web do
    pipe_through :browser

    get "/.well-known/amorphos", PageController, :host_information

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create]

    get "/login", PageController, :login
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete
    get "/switch-user", SessionController, :switch

    get "/timeline", EventController, :timeline

    scope "/yayaka" do
      get "/", YayakaUserController, :index
      get "/user-attributes", YayakaUserController, :user_attributes
      post "/create-user", YayakaUserController, :create_user
      post "/check-user-name-availability", YayakaUserController, :check_user_name_availability
      post "/update-user-name", YayakaUserController, :update_user_name
      post "/update-user-attributes", YayakaUserController, :update_user_attributes
      post "/fetch-user", YayakaUserController, :fetch_user
      post "/fetch-user-by-name", YayakaUserController, :fetch_user_by_name
      post "/get-token", YayakaUserController, :get_token
      post "/authenticate-user", YayakaUserController, :authenticate_user
      post "/authorize-service", YayakaUserController, :authorize_service
      post "/revoke-service-authorization", YayakaUserController, :revoke_service_authorization
      post "/fetch-user-relations", YayakaUserController, :fetch_user_relations
      post "/subscribe", YayakaUserController, :subscribe
      post "/unsubscribe", YayakaUserController, :unsubscribe
    end
  end

  scope "/api", Web do
    pipe_through [:api, :api_auth]

    scope "/amorphos" do
      scope "/https-token" do
        post "/request", HTTPSTokenController, :request
        post "/grant", HTTPSTokenController, :grant
        post "/packet", HTTPSTokenController, :packet
      end
    end
  end
end

apps/web/lib/web/controllers/event_controller.ex
defmodule Web.EventController do
  use Web, :controller

  def timeline(conn, %{"timeline" => params}) do
    %{"social_graph_host" => social_graph_host,
      "identity_host" => identity_host,
      "user_id" => user_id} = params
    data = %{
      social_graph_host: social_graph_host,
      identity_host: identity_host,
      user_id: user_id}
    token = Phoenix.Token.sign(Web.Endpoint, "timeline", data)
    render conn, "timeline.html", token: token
  end

  def timeline(conn, _params) do
    render conn, "timeline.html"
  end
end

apps/web/lib/web/views/event_view.ex
defmodule Web.EventView do
  use Web, :view
end

apps/web/lib/web/templates/event/timeline.html.eex
<%
user = get_yayaka_user(@conn)
user_id = if not is_nil(user), do: user.id, else: ""
%>
<h2>Timeline</h2>
<%= if is_nil(@conn.assigns[:token]) do %>
<div class="ui segment">
  <% opts = [as: :timeline, method: :get, class: "ui form"] %>
  <%= form_for @conn, event_path(@conn, :timeline), opts, fn f -> %>
    <div class="field">
      <%= label f, :social_graph_host, "Social Graph host" %>
      <%= text_input f, :social_graph_host, value: Amorphos.get_host() %>
    </div>
    <div class="field">
      <%= label f, :identity_host, "Identity host" %>
      <%= text_input f, :identity_host, value: Amorphos.get_host() %>
    </div>
    <div class="field">
      <%= label f, :user_id, "User ID" %>
      <%= text_input f, :user_id, value: user_id %>
    </div>
    <%= submit "Show", class: "ui primary button" %>
  <% end %>
</div>
<% else %>
  <%= if not is_nil(user) do %>
    <div class="ui segment">
      <form id="event" class="ui form">
        <div class="field">
          <label for="repository_host">Repository host</label>
          <input type="text" id="repository_host" name="repositor_host" value="<%= Amorphos.get_host() %>">
        </div>
        <div class="field">
          <label for="protocol">Protocol</label>
          <input type="text" id="protocol" name="protocol" value="yayaka">
        </div>
        <div class="field">
          <label for="type">Type</label>
          <input type="text" id="type" name="type" value="post">
        </div>
        <div class="field">
          <label for="body">Body</label>
          <textarea id="body" name="body" rows="11">
{
  "contents": [
    {
      "protocol": "yayaka",
      "type": "plaintext",
      "body": {
        "text": ""
      }
    }
  ]
}
          </textarea>
        </div>
        <%= submit "Submit", class: "ui primary button" %>
      </form>
    </div>
  <% end %>
  <div id="timeline" class="ui list">
  </div>
  <script>
window.timelineToken = "<%= @token %>"
  </script>
  <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
<% end %>